version: "3.4"

services:
  # Upstash Redis local
  upstash_redis:
    image: cloudmix/upstash-redis-local:0.0.3
    depends_on:
      - redis
    ports:
      - 3001:8080
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
  # DynamoDB
  dynamodb:
    image: amazon/dynamodb-local:2.0.0
    ports:
      - 3002:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ."
  # Turso
  turso:
    image: ghcr.io/libsql/sqld:v0.17.2
    ports:
      - 3003:8080
  # Planetscale local
  planetscale:
    image: cloudmix/planetscale-local:0.0.1
    depends_on:
      - mysql
    ports:
      - 3004:8080
    environment:
      - PORT=8080
      - MYSQL_URL=mysql://workertown:workertown@mysql:3306/workertown
  # MYSQL
  mysql:
    image: mysql:8.0.32
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=workertown
      - MYSQL_DATABASE=workertown
      - MYSQL_USER=workertown
      - MYSQL_PASSWORD=workertown
  # Redis
  redis:
    image: redis:6.2.6
    hostname: redis
    command: redis-server --save 60 1 --loglevel warning
  # s3
  s3:
    image: minio/minio:RELEASE.2023-08-09T23-30-22Z
    hostname: minio
    ports:
      - 3005:9000
      - 3006:9001
    environment:
      - MINIO_ROOT_USER=workertown
      - MINIO_ROOT_PASSWORD=workertown
    command: server /data --console-address ":9001"
  # Kafka
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    hostname: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.4.0
    hostname: kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
