name = "search"
main = "src/worker.ts"
compatibility_date = "2023-05-30"

[[kv_namespaces]]
binding = "SEARCH_CACHE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[d1_databases]]
binding = "SEARCH_DB"
database_name = "search_example"
database_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
