name: Test cache adapters

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - "/internal/cache/**"
      - .github/workflows/test-cache-adapters.yml
  workflow_dispatch:

jobs:
  test-cache-adapters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm i

      - name: Start local services
        uses: isbang/compose-action@v1.5.1
        with:
          services: |
            upstash_redis

      - name: Run Tests
        run: pnpm test --filter=@workertown/internal-cache
