name: Test files adapters

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - "/internal/files/**"
      - .github/workflows/test-files-adapters.yml
  workflow_dispatch:

jobs:
  test-files-adapters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm i

      - name: Start local services
        uses: isbang/compose-action@v1.5.1
        with:
          services: |
            upstash-redis
            dynamodb
            turso

      - name: Run Tests
        run: npm run test -- --filter=@workertown/files -- 'test/files/*.e2e.test.ts'
