name: Test @workertown/node

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - packages/node/**
      - .github/workflows/test-node.yml
  workflow_dispatch:

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm i

      - name: Run Tests
        run: pnpm test -- --filter=@workertown/node
