name: Test @workertown/utils

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - packages/utils
      - .github/workflows/test-utils.yml
  workflow_dispatch:

jobs:
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm -w @workertown/utils i

      - name: Run Tests
        run: npm test -- --filter=@workertown/utils
